### PR TITLE
fix index.html description

### PR DESCRIPTION
**Pull request by charlesrocket**

### CODE REVIEW

**Comment by Alex-Werner** [comment]
$root.title is used for populating SEO-stuff in the meta tags, so it should actually work. 
One issue tho, is that when you actually go on a search over Google, it will show that too. 
I'm good with removing that for a simple static description. 

cc: @nmarley

**Comment by nmarley** [comment]
@Alex-Werner Can you explain more what you mean by "when you actually go on a search over Google, it will show that too" ?

**Comment by Cofresi** [comment]
@nmarley I think what @Alex-Werner means is that whatever is in the description tag could end up in the Google results description when somebody is searching for i.e. "insight dash". When you do that though, you will see that Google is not using anything from the html description tag, but rather showing text from the home page of `https://insight.dash.org/insight/`. IMO this PR reduces complexity and is good to go. Will merge if no opposing view shows up during the next few days

**Review by Cofresi — APPROVED** [review]
ACK

**Pull request merged**
