### PR TITLE
Move `dashcore-node.json` config outside root directory

### PR DESCRIPTION
**Pull request by shumkov**

### CODE REVIEW

**Comment by Cofresi** [comment]
Hmmm... I'm still getting the same error when building and running the docker image locally. Do the dashcore-node.json files really need to be included in either insight-api or insight-ui? Maybe include it in the dashcore-node project?

```
Error: Could not load service "@dashevo/insight-ui" as it does not support necessary methods and properties.
    at checkService (/insight/lib/scaffold/start.js:124:11)
    at Function.setupServices (/insight/lib/scaffold/start.js:182:7)
    at start (/insight/lib/scaffold/start.js:85:31)
    at Command.<anonymous> (/insight/lib/cli/main.js:70:7)
    at Command.listener (/insight/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/insight/node_modules/commander/index.js:654:12)
    at Command.parse (/insight/node_modules/commander/index.js:474:21)
    at Object.main (/insight/lib/cli/main.js:147:11)
```

**Comment by shumkov** [comment]
@Cofresi We have two versions for ui and api. Not sure that we need to put them to `dashcore-node`.

**Comment by shumkov** [comment]
@Cofresi I realized what the problem. We install UI package from NPM where still the previous version with the config. During Travis build, a new package without config will be published and everything must be Ok.

**Review by nmarley — APPROVED** [review]
utACK

**Pull request merged**
