### PR TITLE
Upgrade bower in order to fix build

### PR DESCRIPTION
**Pull request by shumkov**

### CODE REVIEW

**Review by Cofresi — DISMISSED** [review]
utACK

**Comment by nmarley** [comment]
@shumkov What is the difference between this and the previous? Has something changed which will ensure this one builds the image correctly?

**Review by nmarley — CHANGES_REQUESTED** [review]
Let's get to root cause before trying again -- there's some logical reason that the npm build script isn't being run before publishing to npm.

**Comment by shumkov** [comment]
@nmarley I've updated bower and now `npm run build` works properly.

**Review by Cofresi — APPROVED** [review]
tested ACK

Seems @snogcel's fix https://github.com/dashevo/insight-ui/pull/44 set bower back to an earlier version which caused the build problem. Fortunately the newest version of bower did not cause the search to malfunction again. I tested the search bar with this fix and everything works as expected.

**Review by nmarley — APPROVED** [review]
slightly tested ACK

Thanks for figuring out the fix!

**Pull request merged**
