### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sa-egor**
Changed package place from "@dashcore" on "@dashevo".

### CODE REVIEW

**Comment by Cofresi** [comment]
Good catch! The branch you want to merge to is outdated though. Can you please close this PR and open a new one which branches off from master branch and merges to master directly.
Thank you!

**Comment by sa-egor** [comment]
> Good catch! The branch you want to merge to is outdated though. Can you please close this PR and open a new one which branches off from master branch and merges to master directly.
> Thank you!

Done.

**Comment by nmarley** [comment]
Nice catch, thanks!

Just an FYI for the future, there's really no need to open a new PR. There is an "edit" button at the top of the page which allows PRs to be modified to update the base branch. Hope that helps!

**Comment by sa-egor** [comment]
Thanks for information.

**Pull request closed without merging**
