### PR TITLE
docs: improved translations and added Dutch translation

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Review by Cofresi — APPROVED** [review]
utACK

**Comment by PanderMusubi** [comment]
Can this PR move a step forward please? Thank.

**Comment by thephez** [comment]
@Cofresi @antouhou @shumkov Is there any reason this hasn't been merged yet?

**Review by shumkov — APPROVED** [review]
👍

**Comment by PanderMusubi** [comment]
When can a deploy be expected on https://explorer.dash.org/insight/ ? (Similar contribution has been deployed already by Firo, see https://explorer.firo.org/ )

**Comment by nmarley** [comment]
As soon as the development team builds and tags a new `dashpay/insight` (not API) image, the infra team can deploy it. There has not been a new image pushed in several months.

**Comment by strophy** [comment]
Building, tagging and pushing docker images is blocked by tests failing in #71

**Comment by PanderMusubi** [comment]
@strophy , I see https://github.com/dashevo/insight-ui/pull/71 has been fixed. Can we move this PR forward now?

**Comment by strophy** [comment]
It looks like this is already merged, the updated translations will be included in the next release of Insight.

**Pull request merged**
