### PR TITLE
fix: adjust address validation to allow p2sh

### PR DESCRIPTION
**Pull request by UdjinM6**
Should allow searching for p2sh addresses (multisig etc.)

Also drop support for non-existing `x` and `Y` prefixes while at it.

Prefixes
mainnet: https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L282-L285
testnet: https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L517-L520 (same for devnet/regtest)

### CODE REVIEW

**Review by strophy — DISMISSED** [review]
LGTM

**Comment by UdjinM6** [comment]
@strophy note: I could not get `npm install` to finish (it fails with lots of errors) so I could not run `npm build` and include the minified version.

**Comment by strophy** [comment]
@UdjinM6 it works for me here, shall I push on this branch with the minified files and a version bump?

**Comment by UdjinM6** [comment]
yes, pls do whatever is needed :)

(btw I tried downgrading to node@16 - it helps with `npm install` but now `npm run build` fails with some bower error...)

**Review by strophy — APPROVED** [review]

**Comment by UdjinM6** [comment]
In case anyone is having the same issue with bower: the reason it fails is because `angular-qrcode` uses `git://` url in dependencies https://github.com/monospaced/angular-qrcode/blob/master/bower.json#L13. This url format is abandoned now https://github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting. However `angular-qrcode` is no longer maintained and replacing url there is not an option. The fix is to force your local `git` to replace all `git://` with `https://`:
```
git config url."https://".insteadOf git://
```

**Pull request merged**
