### PR TITLE
Fix transaction details rendering for small screens

### PR DESCRIPTION
**Pull request by UdjinM6**
| Before | After |
|-|-|
| Screenshot 2021-03-29 at 13 25 13 | Screenshot 2021-03-29 at 13 26 00 |
|-|-|

### CODE REVIEW

**Review by antouhou — APPROVED** [review]
Nice! 👍 utACK

**Comment by antouhou** [comment]
Hm, Travis seems to be upset by something. I'll look into it a bit later

**Comment by UdjinM6** [comment]
Piiiiiiing. This is pretty annoying on mobile... :/

**Comment by antouhou** [comment]
I think we can go ahead and merge it

**Pull request merged**
