### PR TITLE
Fix: Search Bar Redirection

### PR DESCRIPTION
**Pull request by snogcel**
This Pull Request reverts several changes introduced by https://github.com/dashevo/insight-ui/pull/33. 

I found that the following function was not completing as expected and would only work correctly when a Block was being searched for: https://github.com/dashevo/insight-ui/blob/master/public/src/js/controllers/search.js#L26-L62. 

Through trial and error I found that this wasn't caused by the updated dependencies in bower.json, but instead it seems to be related to the updated bower and grunt versions in package.json. I've reverted them to the older version which fixes the problem with the Search Bar.

### CODE REVIEW

**Comment by nmarley** [comment]
Thanks for digging in to this Jon!

Looks like the `npm ci` command is failing w/this error on all versions: `Error: Failed to replace env in config: ${NPM_TOKEN}`. I just checked and `NPM_TOKEN` is definitely set in the Travis settings, so I'm not sure why this would be failing.

@shumkov Do you know if this could be related to the branches filter in `.travis.yml`?

**Comment by shumkov** [comment]
@nmarley @snogcel I would suggest to try this line:
```
npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
```
instead of https://github.com/dashevo/insight-ui/blob/master/.travis.yml#L26

**Comment by snogcel** [comment]
@shumkov thanks I'll give it a try

**Review by Cofresi — APPROVED** [review]
awesome! Super grateful you found the problem 🥇 
utACK

**Review by shumkov — APPROVED** [review]
👍 utACK

**Pull request merged**
